/* This file was generated by syncqt. */
#ifndef QT_QQMLMODELS_VERSION_H
#define QT_QQMLMODELS_VERSION_H

#define QQMLMODELS_VERSION_STR "1.0.0"

#define QQMLMODELS_VERSION 0x010000

#endif // QT_QQMLMODELS_VERSION_H
